version: '3'

services:
  mysql:
    image: mariadb 
    volumes:
      - /Users/waseemmir/Desktop/standalone:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      -  MYSQL_ROOT_PASSWORD:password
      -  MYSQL_DATABASE:chart



  website:
    image: php_mysqli 
    volumes:
      - ./cbcm_new:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - mysql 
    links:
      - mysql
